### PR TITLE
Use reactphp/async instead of clue/reactphp-block

### PR DESCRIPTION
**Pull request by dinooo13**
See https://github.com/reactphp/async

Ref: https://github.com/clue/reactphp-block/pull/67, https://github.com/clue/reactphp-block/issues/68, https://github.com/reactphp/http/pull/464 and https://github.com/clue/reactphp-mq/pull/34

### CODE REVIEW

**Comment by SimonFrings** [comment]
@dinooo13 Thanks for this PR, can you add some references in your PR description similar to my comment in [clue/reactphp-mq#34](https://github.com/clue/reactphp-mq/pull/34).

**Comment by dinooo13** [comment]
Updated with `1.x`, please re-review.

**Review by SimonFrings — APPROVED** [review]
Looks good 👍

**Review by WyriHaximus — APPROVED** [review]

**Review by clue — COMMENTED** [review]
@dinooo13 Changes LGTM, may I ask you to rebase/squash this into a single commit? 👍

**Comment by dinooo13** [comment]
squashed 👍🏼

**Review by clue — APPROVED** [review]
@dinooo13 Thanks for the update, keep it up! :shipit:

**Pull request merged**
